[package]
name = "mbus"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
chromiumoxide = "0.8.0"
chromiumoxide_cdp = "0.8.0"
futures = "0.3"
jsonschema = "0.17"
schemars = { version = "0.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
